region: us-east-1

function_name: canada-trade-leads
handler: service.handler
role: lambda_api
description: Builds a single JSON document of Canada Trade leads and stores it in S3
runtime: python3.8

timeout: 300
memory_size: 128
